In [1]:
!pip install -U transformers peft

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.5.3-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.10.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.12.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.3.5)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.5.3-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 100.2 MB/s eta 0:00:0000:010:01
Downloading huggingface_hub-1.10.1-py3-none-any.whl (642 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 642.6/642.6 kB 34.0 MB/s eta 0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 80.3 MB/s eta 0:00:00:00:01
Installing collected packages: hf-xet, huggingface-hub, transformers
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.3.0
    Uninstalling hf-xet-1.3.0:
      Successfully uninstalled hf-xet-1.3.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed hf-xet-1.4.3 huggingface-hub-1.10.1 transformers-5.5.3

In [2]:
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [3]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

In [4]:
student_model = "google/gemma-3-1b-it"
teacher_model = "Qwen/Qwen3-8B"
device = "cuda" if torch.cuda.is_available() else "cpu" # cuda to increase the pace of learning
dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32

In [5]:
# the student
tokenizerGemma = AutoTokenizer.from_pretrained(student_model)
modelGemma = AutoModelForCausalLM.from_pretrained(
    student_model,
    torch_dtype=dtype, 
    device_map="auto" if torch.cuda.is_available() else None
)

# the teacher
tokenizerQwen = AutoTokenizer.from_pretrained(teacher_model)
modelQwen = AutoModelForCausalLM.from_pretrained(
    teacher_model,
    torch_dtype=dtype,
    device_map="auto" if torch.cuda.is_available() else None
)

if not torch.cuda.is_available():
    modelGemma = modelGemma.to(device)
    modelQwen = modelQwen.to(device)

modelGemma.eval()
modelQwen.eval()

config.json:   0%|          | 0.00/899 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 4096)
    (layers): ModuleList(
      (0-35): 36 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=4096, out_features=12288, bias=False)
          (up_proj): Linear(in_features=4096, out_features=12288, bias=False)
          (down_proj): Linear(in_features=12288, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((4096,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=151936, bias=False)
)

In [6]:
print(type(modelGemma))
print(type(modelQwen))
print(modelGemma.device)
print(modelQwen.device)

<class 'transformers.models.gemma3.modeling_gemma3.Gemma3ForCausalLM'>
<class 'transformers.models.qwen3.modeling_qwen3.Qwen3ForCausalLM'>
cuda:0
cuda:0

In [7]:
if tokenizerGemma.pad_token is None:
    tokenizerGemma.pad_token = tokenizerGemma.eos_token

modelGemma.config.pad_token_id = tokenizerGemma.pad_token_id

In [8]:
def generate_student_answer(model, tokenizer, messages, max_new_tokens=64, **gen_kwargs):
    inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
)

    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = model.generate(
            **inputs, 
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            **gen_kwargs
        )

    prompt_len = inputs['input_ids'].shape[-1]
    new_tokens = outputs[0][prompt_len:]

    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

In [9]:
def generate_teacher_candidates(model, tokenizer, messages, num_candidates=8, max_new_tokens=96):
    text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False,
        enable_thinking=False
    )

    inputs = tokenizer(
        [text],
        return_tensors='pt',
        padding=True,
        truncation=True
    )
    
    inputs = {k: v.to(model.device) for k, v in inputs.items()}
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=1.0,
        top_p=0.95,
        top_k=50,
        num_return_sequences=num_candidates,
        pad_token_id=tokenizer.pad_token_id
    )

    prompt_len = inputs['input_ids'].shape[-1]
    answers = []

    for i in range(outputs.shape[0]):
        new_tokens = outputs[i][prompt_len:]
        answer = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        answers.append(answer)
    
    return answers

In [10]:
def generate_teacher_answer(model, tokenizer, messages, max_new_tokens=96):
    candidates = generate_teacher_candidates(
        model,
        tokenizer,
        messages,
        num_candidates=1,
        max_new_tokens=max_new_tokens
    )
    
    return candidates[0]

In [11]:
from datasets import load_dataset

dataset = load_dataset("HuggingFaceTB/Countdown-Task-GOLD", "all")
train_dataset = dataset['train']

print(dataset)
print(train_dataset)

README.md: 0.00B [00:00, ?B/s]

all/train-00000-of-00001.parquet:   0%|          | 0.00/3.25M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/80000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['target', 'nums', 'prompt'],
        num_rows: 80000
    })
})
Dataset({
    features: ['target', 'nums', 'prompt'],
    num_rows: 80000
})

In [12]:
example = train_dataset[0]
messages = example['prompt']
numbers = example['nums']
target = example['target']

In [13]:
teacher_answer = generate_teacher_answer(modelQwen, tokenizerQwen, messages, max_new_tokens=500)
print(teacher_answer)

To solve this problem, we need to find a way to combine the numbers 75, 80, 90, and 24 using basic arithmetic operations (+, -, *, /) so that the result is 61. Each number must be used exactly once.

Let's analyze the numbers and try different combinations.

We start by considering subtraction, since it's often useful for reducing large numbers. Let's try:

$$
90 - 80 = 10
$$

Now we have 75, 24, and 10 left. Let's try to get 61 from these.

Try:
$$
75 - 24 = 51
$$

Now we have 51 and 10. Try:
$$
51 + 10 = 61
$$

So we have:
$$
(75 - 24) + (90 - 80) = 61
$$

Let's verify:

- $75 - 24 = 51$
- $90 - 80 = 10$
- $51 + 10 = 61$

This satisfies the condition.

<answer> (75 - 24) + (90 - 80) = 61 </answer>

In [14]:
full_train = dataset['train'].shuffle(seed=42)
train_part = full_train.select(range(70000))
eval_part = full_train.select(range(70000, 80000))

# print(len(train_part), len(eval_part))
print(train_part[0].keys())

dict_keys(['target', 'nums', 'prompt'])

# Teacher checkings

In [15]:
from collections import Counter
import re

def extract_answer_block(text):
    matches = re.findall(r'<answer>\s*(.*?)\s*</answer>', text, re.DOTALL)
    if not matches:
        return None

    return matches[-1].strip()


def extract_expression(answer_block):
    if answer_block is None:
        return None

    answer_block = answer_block.strip()
    if '=' in answer_block:
        left, right = answer_block.split('=', 1)
        return left.strip()

    return answer_block


def is_allowed_expression(expression):
    if expression is None:
        return False

    return re.fullmatch(r'[0-9+\-*/().\s]+', expression) is not None


def extract_numbers_from_expression(expression):
    return [int(x) for x in re.findall(r'\d+', expression)]


def uses_numbers_correctly(expression, numbers):
    expression_numbers = extract_numbers_from_expression(expression)
    expression_counter = Counter(expression_numbers)
    numbers_counter = Counter(numbers)

    for number, count in expression_counter.items():
        if count > numbers_counter[number]:
            return False

    return True


def evaluate_expression(expression):
    if not is_allowed_expression(expression):
        return None

    try:
        value = eval(expression, {'__builtins__': None}, {})
        return value
    except Exception:
        return None


def matches_target(value, target, eps=1e-9):
    if value is None:
        return False

    return abs(value - target) < eps

In [16]:
def is_teacher_answer_correct(answer, numbers, target):
    answer_block = extract_answer_block(answer)
    if answer_block is None:
        return False, 'no <answer> block'

    expression = extract_expression(answer_block)
    if expression is None:
        return False, 'no expression'

    if not is_allowed_expression(expression):
        return False, 'forbidden symbols or operations'

    if not uses_numbers_correctly(expression, numbers):
        return False, 'numbers used incorrectly'

    value = evaluate_expression(expression)
    if value is None:
        return False, 'evaluate_expression'

    if not matches_target(value, target):
        return False, f'wrong result: got {value}, expected {target}'

    return True, 'ok'

In [17]:
is_ok, reason = is_teacher_answer_correct(teacher_answer, numbers, target)
print("Correct:", is_ok)
print("Reason:", reason)

Correct: True
Reason: ok

In [18]:
def build_task_messages(example):
    nums = example['nums']
    target = example['target']

    return [
        {
            "role": "user",
            "content": f"""Use numbers {nums} to make {target}.
Rules:
- Use only +, -, *, /
- Use each number at most once
- Do not introduce any new numbers
- Return ONLY one arithmetic expression inside <answer> </answer>
- Do NOT include an equals sign
- Do NOT include explanations
- Do NOT include <think>

Example:
<answer> (13 - 10) * 9 </answer>"""
        }
    ]

In [19]:
def build_teacher_messages(example):
    return build_task_messages(example)

In [20]:
def get_valid_teacher_answer(model, tokenizer, example, num_candidates=8, max_new_tokens=96):
    messages = build_teacher_messages(example)
    nums = example['nums']
    target = example['target']

    candidates = generate_teacher_candidates(
        model,
        tokenizer,
        messages,
        num_candidates=num_candidates,
        max_new_tokens=max_new_tokens
    )

    candidates_info = []
    for candidate in candidates:
        is_ok, reason = is_teacher_answer_correct(candidate, nums, target)
        candidates_info.append((candidate, is_ok, reason))

        if is_ok: 
            return candidate, True, 'ok', candidates_info

    return None, False, 'no valid candidate', candidates_info

In [21]:
def build_teacher_repair_messages(example, bad_answer, reason):
    nums = example['nums']
    target = example['target']

    return [
        {
            "role": "user",
            "content": f"""The previous answer was invalid.

            Numbers: {nums}
            Target: {target}
            Previous answer: {bad_answer}
            Validation error: {reason}
            
            Fix the answer.
            
            Rules:
            - Use only the provided numbers.
            - Use each provided number at most once.
            - Do not introduce new numbers.
            - Return ONLY one arithmetic expression inside <answer> </answer>.
            - Do NOT include an equals sign.
            - Do NOT include explanations.
            
            Example:
            <answer> (13 - 10) * 9 </answer>"""
        }
    ]

In [22]:
def try_teacher_repair(model, tokenizer, example, bad_answer, reason, max_new_tokens=96):
    repair_messages = build_teacher_repair_messages(example, bad_answer, reason)

    repaired_answer = generate_teacher_answer(
        model,
        tokenizer,
        repair_messages,
        max_new_tokens=max_new_tokens
    )

    nums = example['nums']
    target = example['target']

    is_ok, new_reason = is_teacher_answer_correct(repaired_answer, nums, target)
    return repaired_answer, is_ok, new_reason

In [23]:
import math

def solve_4_numbers(nums, target):
    eps = 1e-6

    def dfs(values):
        if len(values) == 1:
            value, expression = values[0]

            if abs(value - target) < eps:
                return expression
            return None

        n = len(values)
        for i in range(n):
            for j in range(n):
                if i == j:
                    continue

                a_value, a_expression = values[i]
                b_value, b_expression = values[j]
                rest = [values[k] for k in range(n) if k != i and k != j]

                candidates = []
                candidates.append((a_value + b_value, f"({a_expression} + {b_expression})"))
                candidates.append((a_value - b_value, f"({a_expression} - {b_expression})"))
                candidates.append((a_value * b_value, f"({a_expression} * {b_expression})"))

                if abs(b_value) > eps:
                    candidates.append((a_value / b_value, f"({a_expression} / {b_expression})"))

                for new_value, new_expression in candidates:
                    result = dfs(rest + [(new_value, new_expression)])

                    if result is not None:
                        return result


        return None
    
    initial = [(float(x), str(x)) for x in nums]
    return dfs(initial)

# Getting synthetic data

In [24]:
synthetic_data = []
correct_answers = 0
total_answers = 0
# reject_reasons = Counter()
bootstrap_subset = train_part.select(range(100))

for example in bootstrap_subset:
    nums = example['nums']
    target = example['target']

    result, is_ok, reason, candidates_info = get_valid_teacher_answer(
        modelQwen,
        tokenizerQwen,
        example,
        num_candidates=3,
        max_new_tokens=96
    )

    total_answers += 1
    if is_ok:
        correct_answers += 1
        synthetic_data.append({
            'prompt': example['prompt'],
            'supervision_answer': result,
            'source': 'teacher',
            'nums': nums,
            'target': target
        })
        
        print('Accepted:', result)
        continue
        
    print('No valid candidate. Candidates:')
    for candidate, cand_ok, cand_reason in candidates_info:
        print(' ', repr(candidate), '|', cand_reason)
    #     reject_reasons[cand_reason] += 1

    solved_expression = solve_4_numbers(nums, target)
    if solved_expression is not None:
        solved_answer = f'<answer> {solved_expression} </answer>'
        correct_answers += 1
        synthetic_data.append({
            'prompt': example['prompt'],
            'supervision_answer': solved_answer,
            'source': 'solver',
            'nums': nums,
            'target': target
        })

        print('Accepted via solver:', solved_answer)
        continue

    bad_answer, _, bad_reason = candidates_info[0]
    repaired_answer, repaired_ok, repaired_reason = try_teacher_repair(
        modelQwen,
        tokenizerQwen,
        example,
        bad_answer,
        bad_reason,
        max_new_tokens=96
    )

    print('Repaired:', repr(repaired_answer))
    if repaired_ok:
        correct_answers += 1
        synthetic_data.append({
            'prompt': example['prompt'],
            'supervision_answer': repaired_answer,
            'source': 'teacher_repair',
            'nums': nums,
            'target': target
        })

        print('Accepted after repair')

    # else:
    #     reject_reasons[repaired_reason] += 1
    #     print('Repair failed:', repaired_reason)
    
teacher_accuracy = correct_answers / total_answers
print('teacher accuracy:', teacher_accuracy)
print('length of synthetic_data', len(synthetic_data))
# print('reject reasons:', reject_reasons)

No valid candidate. Candidates:
  '<answer> 43 + 38 + 14 - 19 </answer>' | wrong result: got 76, expected 89
  '<answer> (43 - 14) + (38 - 19) </answer>' | wrong result: got 48, expected 89
  '<answer> 43 + 38 + 14 - 19 </answer>' | wrong result: got 76, expected 89
Accepted via solver: <answer> (19 - (14 * (38 - 43))) </answer>
No valid candidate. Candidates:
  '<answer> (88 - 82) * (76 - 25) </answer>' | wrong result: got 306, expected 50
  '<answer> (88 - 82) * (76 - 25) </answer>' | wrong result: got 306, expected 50
  '<answer> (88 - 82) * (76 - 25) </answer>' | wrong result: got 306, expected 50
Accepted via solver: <answer> ((88 + 76) / (82 / 25)) </answer>
No valid candidate. Candidates:
  '<answer> (73 - 67) * (34 - 30) </answer>' | numbers used incorrectly
  '<answer> 73 - 67 - 34 </answer>' | wrong result: got -28, expected 40
  '<answer> (73 - 67) * (34 - 34) </answer>' | numbers used incorrectly
Accepted via solver: <answer> (73 + (34 - 67)) </answer>
No valid candidate. Candidates:
  '<answer> (93 - 78) - 46 </answer>' | wrong result: got -31, expected 61
  '<answer> (93 - 78) - (46 / 2) </answer>' | numbers used incorrectly
  '<answer> (93 - 78) - (46 / 2) </answer>' | numbers used incorrectly
Accepted via solver: <answer> (93 - (78 - 46)) </answer>
No valid candidate. Candidates:
  '<answer> (49 - 33) - (26 - 4) </answer>' | wrong result: got -6, expected 28
  '<answer> (49 - 33) - (26 - 4) </answer>' | wrong result: got -6, expected 28
  '<answer> (49 - 33) - (26 - 4) </answer>' | wrong result: got -6, expected 28
Accepted via solver: <answer> ((49 * 4) / (33 - 26)) </answer>
No valid candidate. Candidates:
  '<answer> (62 - 36) + (54 - 20) </answer>' | wrong result: got 60, expected 64
  '<answer> (62 - 36) + (54 - 20) </answer>' | wrong result: got 60, expected 64
  '<answer> (62 - 36) + (54 - 20) </answer>' | wrong result: got 60, expected 64
Accepted via solver: <answer> ((62 + 36) + (20 - 54)) </answer>
No valid candidate. Candidates:
  '<answer> (95 - 67) - 73 </answer>' | wrong result: got -45, expected 45
  '<answer> (95 - 67) - 73 </answer>' | wrong result: got -45, expected 45
  '<answer> 95 - 67 - 73 </answer>' | wrong result: got -45, expected 45
Accepted via solver: <answer> (73 - (95 - 67)) </answer>
No valid candidate. Candidates:
  '<answer> (36 - 23) * (32 / 19) </answer>' | wrong result: got 21.89473684210526, expected 99
  '<answer> 36 + 32 + 23 + 19 </answer>' | wrong result: got 110, expected 99
  '<answer> (36 - 23) * (32 - 19) </answer>' | wrong result: got 169, expected 99
Accepted via solver: <answer> (23 + (19 * (36 - 32))) </answer>
No valid candidate. Candidates:
  '<answer> (32 - 21) - (17 - 2) </answer>' | wrong result: got -4, expected 13
  '<answer> (32 - 21) - (17 - 2) </answer>' | wrong result: got -4, expected 13
  '<answer> (32 - 21) - (17 - 2) </answer>' | wrong result: got -4, expected 13
Accepted via solver: <answer> (32 - ((17 + 21) / 2)) </answer>
No valid candidate. Candidates:
  '<answer> (57 - 54) + (52 - 23) </answer>' | wrong result: got 32, expected 11
  '<answer> (57 - 54) + (52 - 23) </answer>' | wrong result: got 32, expected 11
  '<answer> (57 - 54) + (52 - 23) </answer>' | wrong result: got 32, expected 11
Accepted via solver: <answer> (57 - (23 * (54 - 52))) </answer>
No valid candidate. Candidates:
  '<answer> (74 - 70) * (18 - 3) </answer>' | wrong result: got 60, expected 82
  '<answer> 74 - (70 - (18 + 3)) </answer>' | wrong result: got 25, expected 82
  '<answer> (74 - 70) * (18 - 3) </answer>' | wrong result: got 60, expected 82
Accepted via solver: <answer> ((3 * (70 - 18)) - 74) </answer>
No valid candidate. Candidates:
  '<answer> (78 - 67) + (67 / 67) </answer>' | numbers used incorrectly
  '<answer> (78 - 67) + 67 </answer>' | wrong result: got 78, expected 77
  '<answer> (78 - 67) + 67 </answer>' | wrong result: got 78, expected 77
Accepted via solver: <answer> (78 - (67 / 67)) </answer>
No valid candidate. Candidates:
  '<answer> (88 - 67) - (89 - 28) </answer>' | wrong result: got -40, expected 39
  '<answer> 88 - 67 - (89 - 28) </answer>' | wrong result: got -40, expected 39
  '<answer> 88 - 67 - (89 - 28) </answer>' | wrong result: got -40, expected 39
Accepted via solver: <answer> ((28 - 67) * (88 - 89)) </answer>
No valid candidate. Candidates:
  '<answer> (94 - 79) - 46 </answer>' | wrong result: got -31, expected 61
  '<answer> (94 - 79) - 46 </answer>' | wrong result: got -31, expected 61
  '<answer> 94 - 79 - 46 </answer>' | wrong result: got -31, expected 61
Accepted via solver: <answer> (94 + (46 - 79)) </answer>
No valid candidate. Candidates:
  '<answer> 36 - 31 - (84 / 21) </answer>' | wrong result: got 1.0, expected 20
  '<answer> 36 - 31 - (84 / 21) </answer>' | wrong result: got 1.0, expected 20
  '<answer> (84 - 36) / (31 - 21) </answer>' | wrong result: got 4.8, expected 20
Accepted via solver: <answer> ((36 - 31) / (21 / 84)) </answer>
Accepted: <answer> 37 + 17 - 1 </answer>
No valid candidate. Candidates:
  '<answer> 36 - 35 - 7 + 7 </answer>' | wrong result: got 1, expected 30
  '<answer> 36 - 7 - 7 - 35 </answer>' | wrong result: got -13, expected 30
  '<answer> 36 - 7 - 35 + 7 </answer>' | wrong result: got 1, expected 30
Accepted via solver: <answer> (36 - ((35 + 7) / 7)) </answer>
No valid candidate. Candidates:
  '<answer> (90 - 63) - (86 - 16) </answer>' | wrong result: got -43, expected 81
  '<answer> (90 - 63) - (86 - 16) </answer>' | wrong result: got -43, expected 81
  '<answer> (90 - 63) - (86 - 16) </answer>' | wrong result: got -43, expected 81
Accepted via solver: <answer> ((90 * 63) / (86 - 16)) </answer>
No valid candidate. Candidates:
  '<answer> 13 + 10 + 9 - 5 </answer>' | numbers used incorrectly
  '<answer> 13 + 10 + 9 - 5 </answer>' | numbers used incorrectly
  '<answer> 13 + 10 + 9 - 5 </answer>' | numbers used incorrectly
Accepted via solver: <answer> (9 * (13 - 10)) </answer>
No valid candidate. Candidates:
  '<answer> 67 - 11 - 3 * 2 </answer>' | numbers used incorrectly
  '<answer> (67 - 11) / 3 </answer>' | wrong result: got 18.666666666666668, expected 59
  '<answer> 67 - 11 - 3 </answer>' | wrong result: got 53, expected 59
Accepted via solver: <answer> (3 - (11 - 67)) </answer>
No valid candidate. Candidates:
  '<answer> 62 - 46 - 30 </answer>' | wrong result: got -14, expected 14
  '<answer> (62 - 46) - 30 </answer>' | wrong result: got -14, expected 14
  '<answer> (62 - 46) - (30 / 30) </answer>' | numbers used incorrectly
Accepted via solver: <answer> (30 + (46 - 62)) </answer>
No valid candidate. Candidates:
  '<answer> (55 - 47) * (5 - (12 / 12)) </answer>' | numbers used incorrectly
  '<answer> (55 - 47) * (5 - 12 / 5) </answer>' | numbers used incorrectly
  '<answer> 55 - 47 - (12 / 5) </answer>' | wrong result: got 5.6, expected 48
Accepted via solver: <answer> ((12 + 47) - (55 / 5)) </answer>
No valid candidate. Candidates:
  '<answer> (54 - 18) / (54 - 12) </answer>' | wrong result: got 0.8571428571428571, expected 30
  '<answer> (54 - 18) / (54 - 12) </answer>' | wrong result: got 0.8571428571428571, expected 30
  '<answer> 54 / 18 + 54 - 12 </answer>' | wrong result: got 45.0, expected 30
Accepted via solver: <answer> ((18 + 12) + (54 - 54)) </answer>
No valid candidate. Candidates:
  '<answer> (97 - 54) - (79 - 41) </answer>' | wrong result: got 5, expected 38
  '<answer> (97 - 54) - (79 - 41) </answer>' | wrong result: got 5, expected 38
  '<answer> (97 - 54) - (79 - 41) </answer>' | wrong result: got 5, expected 38
Accepted via solver: <answer> (41 - (54 / (97 - 79))) </answer>
No valid candidate. Candidates:
  '<answer> (98 - 31) - (83 - 26) </answer>' | wrong result: got 10, expected 75
  '<answer> (98 - 31) - (83 - 26) </answer>' | wrong result: got 10, expected 75
  '<answer> (98 - 31) - (83 - 26) </answer>' | wrong result: got 10, expected 75
Accepted via solver: <answer> ((26 - 31) * (83 - 98)) </answer>
No valid candidate. Candidates:
  '<answer> 23 * (47 - 29 - 18) </answer>' | wrong result: got 0, expected 23
  '<answer> 23 * (47 - 29 - 18) </answer>' | wrong result: got 0, expected 23
  '<answer> 47 - 23 - 18 - 29 </answer>' | wrong result: got -23, expected 23
Accepted via solver: <answer> ((29 - 47) + (23 + 18)) </answer>
Accepted: <answer> 96 - 55 + 48 </answer>
Accepted: <answer> 43 + 41 + 13 </answer>
No valid candidate. Candidates:
  '<answer> (29 - 17) * (12 - 3) </answer>' | wrong result: got 108, expected 82
  '<answer> (29 - 17) * (12 - 3) </answer>' | wrong result: got 108, expected 82
  '<answer> (29 - 17) * (12 - 3) </answer>' | wrong result: got 108, expected 82
Accepted via solver: <answer> ((12 - 17) + (29 * 3)) </answer>
No valid candidate. Candidates:
  '<answer> (86 - 72) - (16 / 7) </answer>' | wrong result: got 11.714285714285715, expected 14
  '<answer> (86 - 72) - (16 - 7) </answer>' | wrong result: got 5, expected 14
  '<answer> (86 - 72) - (16 - 7) </answer>' | wrong result: got 5, expected 14
Accepted via solver: <answer> (7 * ((16 + 72) - 86)) </answer>
No valid candidate. Candidates:
  '<answer> 87 - 26 - 25 </answer>' | wrong result: got 36, expected 86
  '<answer> 87 - 26 - 25 </answer>' | wrong result: got 36, expected 86
  '<answer> 87 - 26 - 25 </answer>' | wrong result: got 36, expected 86
Accepted via solver: <answer> (25 + (87 - 26)) </answer>
No valid candidate. Candidates:
  '<answer> 89 + 1 + 2 + 1 </answer>' | numbers used incorrectly
  '<answer> 89 + 1 + 2 + 1 </answer>' | numbers used incorrectly
  '<answer> 89 + 1 + 2 + 1 </answer>' | numbers used incorrectly
Accepted via solver: <answer> ((10 / 2) + (89 - 1)) </answer>
No valid candidate. Candidates:
  '<answer> 62 + 13 - 4 </answer>' | wrong result: got 71, expected 79
  '<answer> 62 + 13 - 4 </answer>' | wrong result: got 71, expected 79
  '<answer> 62 + 13 - 4 </answer>' | wrong result: got 71, expected 79
Accepted via solver: <answer> (4 + (13 + 62)) </answer>
No valid candidate. Candidates:
  '<answer> 80 + 6 + 2 * 2 </answer>' | numbers used incorrectly
  '<answer> 80 + 6 + 2 * 6 </answer>' | numbers used incorrectly
  '<answer> 80 + 6 + 2 * 2 </answer>' | numbers used incorrectly
Accepted via solver: <answer> (80 + (6 * 2)) </answer>
No valid candidate. Candidates:
  '<answer> 59 - 24 - 6 </answer>' | wrong result: got 29, expected 55
  '<answer> 59 - 24 - 6 </answer>' | wrong result: got 29, expected 55
  '<answer> 59 - 24 - 6 </answer>' | wrong result: got 29, expected 55
Accepted via solver: <answer> (59 - (24 / 6)) </answer>
Accepted: <answer> 76 - 33 - 25 </answer>
No valid candidate. Candidates:
  '<answer> 58 + 26 - 46 </answer>' | wrong result: got 38, expected 78
  '<answer> (58 - 46) * 26 </answer>' | wrong result: got 312, expected 78
  '<answer> 58 - 46 + 26 </answer>' | wrong result: got 38, expected 78
Accepted via solver: <answer> (46 - (26 - 58)) </answer>
No valid candidate. Candidates:
  '<answer> 67 - 62 - (64 / 64) </answer>' | numbers used incorrectly
  '<answer> 67 - 62 - (64 / 64) </answer>' | numbers used incorrectly
  '<answer> 67 - 62 - (64 / 64) </answer>' | numbers used incorrectly
Accepted via solver: <answer> ((64 + 62) - 67) </answer>
No valid candidate. Candidates:
  '<answer> (53 - 47) + (26 - 25) </answer>' | wrong result: got 7, expected 50
  '<answer> (53 - 47) + (26 - 25) </answer>' | wrong result: got 7, expected 50
  '<answer> 25 + (53 - 47 - 26) </answer>' | wrong result: got 5, expected 50
Accepted via solver: <answer> (47 + ((25 + 53) / 26)) </answer>
No valid candidate. Candidates:
  '<answer> 81 - 87 + 24 - 8 </answer>' | wrong result: got 10, expected 72
  '<answer> 81 - 87 + 24 - 8 </answer>' | wrong result: got 10, expected 72
  '<answer> 81 - 87 + 24 - 8 </answer>' | wrong result: got 10, expected 72
Accepted via solver: <answer> (24 + (8 * (87 - 81))) </answer>
Accepted: <answer> (82 - 66) + (71 - 11) </answer>
Accepted: <answer> (54 - 32) + (86 - 25) </answer>
No valid candidate. Candidates:
  '<answer> (50 - 26) - (28 - 9) </answer>' | wrong result: got 5, expected 27
  '<answer> 50 - 26 - (9 + 28) </answer>' | wrong result: got -13, expected 27
  '<answer> (50 - 26) - (28 - 9) </answer>' | wrong result: got 5, expected 27
Accepted via solver: <answer> ((28 + 50) * (9 / 26)) </answer>
No valid candidate. Candidates:
  '<answer> (42 - 21) - (11 + 2) </answer>' | wrong result: got 8, expected 12
  '<answer> (42 - 21) - (11 + 2) </answer>' | wrong result: got 8, expected 12
  '<answer> (42 - 21) - (11 + 2) </answer>' | wrong result: got 8, expected 12
Accepted via solver: <answer> (2 - (21 + (11 - 42))) </answer>
No valid candidate. Candidates:
  '<answer> 84 - 82 - (61 - 39) </answer>' | wrong result: got -20, expected 66
  '<answer> 84 - 82 - (61 - 39) </answer>' | wrong result: got -20, expected 66
  '<answer> (84 - 82) * (61 - 39) </answer>' | wrong result: got 44, expected 66
Accepted via solver: <answer> ((82 + 84) - (61 + 39)) </answer>
Accepted: <answer> 76 + 64 - 46 </answer>
No valid candidate. Candidates:
  '<answer> 60 / (10 + 7) - 23 </answer>' | wrong result: got -19.470588235294116, expected 13
  '<answer> (7 + 10) - (23 - 60) </answer>' | wrong result: got 54, expected 13
  '<answer> 60 / 10 - 7 - 23 </answer>' | wrong result: got -24.0, expected 13
Accepted via solver: <answer> (23 - ((60 + 10) / 7)) </answer>
No valid candidate. Candidates:
  '<answer> (86 - 67) - (84 - 14) </answer>' | wrong result: got -51, expected 60
  '<answer> (86 - 67) - (84 - 14) </answer>' | wrong result: got -51, expected 60
  '<answer> (86 - 67) - (14 + 84) </answer>' | wrong result: got -79, expected 60
Accepted via solver: <answer> (67 - (14 / (86 - 84))) </answer>
No valid candidate. Candidates:
  '<answer> (77 - 42) + (74 - 20) </answer>' | wrong result: got 89, expected 99
  '<answer> (77 - 42) + (74 - 20) </answer>' | wrong result: got 89, expected 99
  '<answer> 77 + 42 - 74 + 20 </answer>' | wrong result: got 65, expected 99
Accepted via solver: <answer> ((74 - 20) / (42 / 77)) </answer>
No valid candidate. Candidates:
  '<answer> 95 - 51 - 49 + 7 </answer>' | wrong result: got 2, expected 86
  '<answer> 95 - 51 - 49 + 7 </answer>' | wrong result: got 2, expected 86
  '<answer> (95 - 51) - (49 - 7) </answer>' | wrong result: got 2, expected 86
Accepted via solver: <answer> ((95 + 49) - (7 + 51)) </answer>
No valid candidate. Candidates:
  '<answer> 86 - 50 - 10 - 7 </answer>' | wrong result: got 19, expected 13
  '<answer> (86 - 50) - (10 + 7) </answer>' | wrong result: got 19, expected 13
  '<answer> 86 - 50 - 10 - 7 </answer>' | wrong result: got 19, expected 13
Accepted via solver: <answer> ((86 + (50 / 10)) / 7) </answer>
No valid candidate. Candidates:
  '<answer> 44 - 26 - 14 </answer>' | wrong result: got 4, expected 32
  '<answer> (44 - 26) - 14 </answer>' | wrong result: got 4, expected 32
  '<answer> (44 - 26) - 14 </answer>' | wrong result: got 4, expected 32
Accepted via solver: <answer> (14 - (26 - 44)) </answer>
No valid candidate. Candidates:
  '<answer> 88 - 82 - 13 + 98 </answer>' | wrong result: got 91, expected 20
  '<answer> (88 - 98) + (82 - 13) </answer>' | wrong result: got 59, expected 20
  '<answer> 88 - 82 - (98 - 13) </answer>' | wrong result: got -79, expected 20
Accepted via solver: <answer> (98 + (13 * (82 - 88))) </answer>
No valid candidate. Candidates:
  '<answer> (98 - 60) - (14 * 2) </answer>' | numbers used incorrectly
  '<answer> (98 - 60) - (14 * 2) </answer>' | numbers used incorrectly
  '<answer> (98 - 60) - (14 * 2) </answer>' | numbers used incorrectly
Accepted via solver: <answer> ((98 - 14) - 60) </answer>
Accepted: <answer> 64 + 36 - 30 </answer>
No valid candidate. Candidates:
  '<answer> 90 - 61 - 2 </answer>' | wrong result: got 27, expected 58
  '<answer> 90 - 61 - 2 </answer>' | wrong result: got 27, expected 58
  '<answer> 90 - 61 - 2 </answer>' | wrong result: got 27, expected 58
Accepted via solver: <answer> (2 * (90 - 61)) </answer>
No valid candidate. Candidates:
  '<answer> 64 - 57 + 5 + 4 </answer>' | wrong result: got 16, expected 92
  '<answer> 64 - (57 - (5 + 4)) </answer>' | wrong result: got 16, expected 92
  '<answer> (64 - 57) * 5 + 4 </answer>' | wrong result: got 39, expected 92
Accepted via solver: <answer> ((64 * 5) - (4 * 57)) </answer>
Accepted: <answer> (77 - 53) + 40 </answer>
No valid candidate. Candidates:
  '<answer> (89 - 38) - (34 + 20) </answer>' | wrong result: got -3, expected 65
  '<answer> 89 - 38 - 20 - 34 </answer>' | wrong result: got -3, expected 65
  '<answer> 89 - 38 - 20 - 34 </answer>' | wrong result: got -3, expected 65
Accepted via solver: <answer> (34 - (20 + (38 - 89))) </answer>
No valid candidate. Candidates:
  '<answer> (54 - 48) + (34 - 30) </answer>' | wrong result: got 10, expected 37
  '<answer> 48 - 30 - (54 - 34) </answer>' | wrong result: got -2, expected 37
  '<answer> (54 - 48) + (34 - 30) </answer>' | wrong result: got 10, expected 37
Accepted via solver: <answer> (34 - (54 / (30 - 48))) </answer>
No valid candidate. Candidates:
  '<answer> (63 - 16) + (13 - 2) </answer>' | wrong result: got 58, expected 97
  '<answer> 63 + 16 + 13 + 2 </answer>' | wrong result: got 94, expected 97
  '<answer> 63 + 16 + 13 + 2 </answer>' | wrong result: got 94, expected 97
Accepted via solver: <answer> ((2 * 63) - (16 + 13)) </answer>
Accepted: <answer> 92 - 11 + 6 </answer>
No valid candidate. Candidates:
  '<answer> (66 - 64) * (15 - 11) </answer>' | wrong result: got 8, expected 35
  '<answer> (66 - 64) * (15 - 11) </answer>' | wrong result: got 8, expected 35
  '<answer> (66 - 64) * (15 - 11) </answer>' | wrong result: got 8, expected 35
Accepted via solver: <answer> ((15 * 11) - (66 + 64)) </answer>
No valid candidate. Candidates:
  '<answer> (62 - 42) - (16 / 4) </answer>' | numbers used incorrectly
  '<answer> 62 - 16 - 42 </answer>' | wrong result: got 4, expected 36
  '<answer> 62 - 42 - 16 </answer>' | wrong result: got 4, expected 36
Accepted via solver: <answer> ((62 + 16) - 42) </answer>
No valid candidate. Candidates:
  '<answer> (93 - 63) - (40 - 20) </answer>' | wrong result: got 10, expected 31
  '<answer> (93 - 63) - (40 - 20) </answer>' | wrong result: got 10, expected 31
  '<answer> (93 - 63) - (40 - 20) </answer>' | wrong result: got 10, expected 31
Accepted via solver: <answer> (93 / (63 - (40 + 20))) </answer>
No valid candidate. Candidates:
  '<answer> 96 - 84 - 3 + 23 </answer>' | wrong result: got 32, expected 33
  '<answer> (96 - 84) + (3 * 23) </answer>' | wrong result: got 81, expected 33
  '<answer> 96 - 84 - 3 - 23 </answer>' | wrong result: got -14, expected 33
Accepted via solver: <answer> (3 * ((23 + 84) - 96)) </answer>
No valid candidate. Candidates:
  '<answer> 89 - 28 - 1 </answer>' | wrong result: got 60, expected 62
  '<answer> 89 - 28 - 1 </answer>' | wrong result: got 60, expected 62
  '<answer> 89 - 28 - 1 </answer>' | wrong result: got 60, expected 62
Accepted via solver: <answer> ((1 + 89) - 28) </answer>
No valid candidate. Candidates:
  '<answer> (86 - 46) / 43 </answer>' | wrong result: got 0.9302325581395349, expected 23
  '<answer> 86 - 43 - 46 </answer>' | wrong result: got -3, expected 23
  '<answer> (86 - 46) / (43 - 13) </answer>' | numbers used incorrectly
Accepted via solver: <answer> (46 / (86 / 43)) </answer>
No valid candidate. Candidates:
  '<answer> (91 - 67) - 11 </answer>' | wrong result: got 13, expected 35
  '<answer> (91 - 67) - 11 </answer>' | wrong result: got 13, expected 35
  '<answer> (91 - 67) - 11 </answer>' | wrong result: got 13, expected 35
Accepted via solver: <answer> (11 + (91 - 67)) </answer>
No valid candidate. Candidates:
  '<answer> 57 + 8 - 6 </answer>' | wrong result: got 59, expected 71
  '<answer> 57 + 8 - 6 </answer>' | wrong result: got 59, expected 71
  '<answer> 57 + 8 - 6 </answer>' | wrong result: got 59, expected 71
Accepted via solver: <answer> (57 + (6 + 8)) </answer>
No valid candidate. Candidates:
  '<answer> 65 - 91 + 1 </answer>' | wrong result: got -25, expected 26

In [25]:
def build_student_messages(example):
    return build_task_messages(example)

In [26]:
def build_student_sft_example(example, tokenizer, max_length=256):
    messages = build_student_messages(example)
    answer = example['supervision_answer'].strip()

    prompt_tokens = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True
    )

    prompt_ids = prompt_tokens['input_ids']

    answer_ids = tokenizer(
        answer + tokenizer.eos_token,
        add_special_tokens=False
    )['input_ids']

    input_ids = prompt_ids + answer_ids
    input_ids = input_ids[:max_length]

    attention_mask = [1] * len(input_ids)

    prompt_len = min(len(prompt_ids), len(input_ids))
    labels = [-100] * prompt_len + input_ids[prompt_len:]

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'labels': labels
    }

In [27]:
sample = build_student_sft_example(synthetic_data[0], tokenizerGemma, max_length=256)

label_ids = [x for x in sample['labels'] if x != -100]

print('Num supervised tokens:', len(label_ids))
print('Decoded supervised text:')
print(tokenizerGemma.decode(label_ids))

Num supervised tokens: 23
Decoded supervised text:
<answer> (19 - (14 * (38 - 43))) </answer><eos>

In [28]:
sample = build_student_sft_example(synthetic_data[0], tokenizerGemma, max_length=256)

print("Decoded full input:")
print(tokenizerGemma.decode(sample["input_ids"]))
print()
print("Decoded supervised target:")
label_ids = [x for x in sample["labels"] if x != -100]
print(tokenizerGemma.decode(label_ids))

Decoded full input:
<bos><start_of_turn>user
Use numbers [38, 19, 43, 14] to make 89.
Rules:
- Use only +, -, *, /
- Use each number at most once
- Do not introduce any new numbers
- Return ONLY one arithmetic expression inside <answer> </answer>
- Do NOT include an equals sign
- Do NOT include explanations
- Do NOT include <think>

Example:
<answer> (13 - 10) * 9 </answer><end_of_turn>
<start_of_turn>model
<answer> (19 - (14 * (38 - 43))) </answer><eos>

Decoded supervised target:
<answer> (19 - (14 * (38 - 43))) </answer><eos>

In [29]:
def debug_supervision_alignment(dataset_list, tokenizer, n=20):
    for i in range(min(n, len(dataset_list))):
        sample = build_student_sft_example(dataset_list[i], tokenizer, max_length=256)
        label_ids = [x for x in sample['labels'] if x != -100]
        decoded_labels = tokenizer.decode(label_ids, skip_special_tokens=False)
        expected = dataset_list[i]['supervision_answer'].strip() + tokenizer.eos_token

        print(f"\n--- Example {i} ---")
        print("EXPECTED:")
        print(repr(expected))
        print("DECODED LABELS:")
        print(repr(decoded_labels))

        if expected != decoded_labels:
            print("MISMATCH !!!")
            return

    print("\nAll checked examples look aligned.")

In [30]:
from datasets import Dataset

In [31]:
def preprocess_student(example):
    return build_student_sft_example(example, tokenizerGemma, max_length=256)

In [32]:
student_sft_dataset = Dataset.from_list(synthetic_data)
tokenized_student_dataset = student_sft_dataset.map(
    preprocess_student,
    remove_columns=student_sft_dataset.column_names
)

print(tokenized_student_dataset[0].keys())

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

dict_keys(['input_ids', 'attention_mask', 'labels'])

In [33]:
from transformers import Trainer, TrainingArguments, DataCollatorForSeq2Seq
from peft import LoraConfig, get_peft_model, TaskType

In [34]:
lora_config = LoraConfig(
    r=16, 
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias='none',
    task_type=TaskType.CAUSAL_LM
)

modelGemma = get_peft_model(modelGemma, lora_config)
modelGemma.print_trainable_parameters()

trainable params: 13,045,760 || all params: 1,012,931,712 || trainable%: 1.2879

In [35]:
training_args = TrainingArguments(
    output_dir='./gemma_student_sft',
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    num_train_epochs=2,
    learning_rate=2e-4,
    weight_decay=0.01,
    logging_steps=10,
    save_steps=200,
    bf16=torch.cuda.is_available(),
    report_to='none'
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizerGemma, 
    model=modelGemma,
    padding=True
)

trainer = Trainer(
    model=modelGemma,
    args=training_args,
    train_dataset=tokenized_student_dataset,
    data_collator=data_collator
)

trainer.train()

TrainOutput(global_step=14, training_loss=0.8540442500795636, metrics={'train_runtime': 97.7676, 'train_samples_per_second': 2.046, 'train_steps_per_second': 0.143, 'total_flos': 115317607620096.0, 'train_loss': 0.8540442500795636, 'epoch': 2.0})

# Evaluate student

In [36]:
def evaluate_student(eval_subset, modelGemma, tokenizerGemma, max_new_tokens=96):
    correct_answers = 0
    total_answers = 0

    for example in eval_subset:
        prompt = build_student_messages(example)
        nums = example['nums']
        target = example['target']

        student_answer = generate_student_answer(
            modelGemma,
            tokenizerGemma,
            prompt,
            max_new_tokens=max_new_tokens
        )
        
        is_ok, _ = is_teacher_answer_correct(student_answer, nums, target)
        total_answers += 1

        if is_ok:
            correct_answers += 1

    task_accuracy = correct_answers / total_answers

    return {
        'task_accuracy': task_accuracy,
        'correct_answers': correct_answers,
        'total_answers': total_answers
    }

In [37]:
modelGemma.gradient_checkpointing_disable()
modelGemma.config.use_cache = True
modelGemma.eval()

train_debug = train_part.select(range(20))
print(evaluate_student(train_debug, modelGemma, tokenizerGemma, max_new_tokens=96))

The following generation flags are not valid and may be ignored: ['top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

{'task_accuracy': 0.1, 'correct_answers': 2, 'total_answers': 20}

In [38]:
debug_subset = eval_part.select(range(5))

for i, example in enumerate(debug_subset):
    prompt = build_student_messages(example)
    answer = generate_student_answer(
        modelGemma,
        tokenizerGemma,
        prompt,
        max_new_tokens=96
    )
    
    print(f"\n--- Example {i} ---")
    print("Target:", example["target"])
    print("Nums:", example["nums"])
    print("Student output:")
    print(repr(answer))

--- Example 0 ---
Target: 27
Nums: [64, 2, 52, 17]
Student output:
'<answer> ((64 + 2) - (52 + 17)) </answer>'

--- Example 1 ---
Target: 28
Nums: [93, 33, 22, 17]
Student output:
'<answer> ((93 + 33) - (22 + 17)) </answer>'

--- Example 2 ---
Target: 71
Nums: [25, 56, 73, 29]
Student output:
'<answer> (25 + 56 - 73) </answer>'

--- Example 3 ---
Target: 85
Nums: [17, 81, 78, 10]
Student output:
'<answer> ((17 + 81) - (78 + 10)) </answer>'

--- Example 4 ---
Target: 98
Nums: [55, 2, 45]
Student output:
'<answer> (55 + 2) - (45 + 55) </answer>'

In [39]:
eval_before_gold = evaluate_student(
    eval_part.select(range(50)),
    modelGemma, 
    tokenizerGemma,
    max_new_tokens=96
)

print('before GOLD:', eval_before_gold)

before GOLD: {'task_accuracy': 0.12, 'correct_answers': 6, 'total_answers': 50}

# GOLD

In [40]:
gold_examples = []
gold_subset = train_part.select(range(100, 200))
student_correct = 0
teacher_fixed = 0
rejected = 0
total_examples = 0

for example in gold_subset:
    prompt = build_student_messages(example)
    nums = example['nums']
    target = example['target']
    total_examples += 1

    student_answer = generate_student_answer(
        modelGemma,
        tokenizerGemma,
        prompt,
        max_new_tokens=96
    )
    
    student_ok, student_reason = is_teacher_answer_correct(student_answer, nums, target)
    if student_ok:
        student_correct += 1
        gold_examples.append({
            'prompt': prompt,
            'supervision_answer': student_answer,
            'source': 'student',
            'nums': nums,
            'target': target
        })
        continue

    repaired_answer, repaired_ok, repaired_reason = try_teacher_repair(
        modelQwen,
        tokenizerQwen,
        example,
        student_answer,
        student_reason,
        max_new_tokens=96
    )

    if repaired_ok:
        teacher_fixed += 1
        gold_examples.append({
            'prompt': prompt,
            'supervision_answer': repaired_answer,
            'source': 'teacher_repair',
            'nums': nums,
            'target': target
        })
        
    else:       
        rejected += 1
            # print('Rejected example')
            # print('Student failed:', student_reason)
            # print('Teacher repair failed:', repaired_reason)

print(student_correct)
print(teacher_fixed)
print(rejected)
print(total_examples)

5
14
81
100

# Accuracy

In [41]:
task_accuracy = (student_correct + teacher_fixed) / total_examples if total_examples > 0 else 0
student_self_success_rate = student_correct / total_examples if total_examples > 0 else 0
teacher_repair_rate = teacher_fixed / total_examples if total_examples > 0 else 0
rejection_rate = rejected / total_examples if total_examples > 0 else 0

print('task_accuracy:', task_accuracy)
print('student_self_success_rate:', student_self_success_rate)
print('teacher_repair_rate:', teacher_repair_rate)
print('rejection_rate:', rejection_rate)
print('length of gold_examples:', len(gold_examples))

task_accuracy: 0.19
student_self_success_rate: 0.05
teacher_repair_rate: 0.14
rejection_rate: 0.81
length of gold_examples: 19

In [42]:
import random

student_gold = [x for x in gold_examples if x['source'] == 'student']
repair_gold = [x for x in gold_examples if x['source'] != 'student']

random.shuffle(repair_gold)
repair_gold = repair_gold[:len(student_gold) * 2] if len(student_gold) > 0 else repair_gold[:20]

gold_examples_balanced = student_gold + repair_gold
random.shuffle(gold_examples_balanced)

print("Before balancing:", Counter(x['source'] for x in gold_examples))
print("After balancing:", Counter(x['source'] for x in gold_examples_balanced))

Before balancing: Counter({'teacher_repair': 14, 'student': 5})
After balancing: Counter({'teacher_repair': 10, 'student': 5})

In [43]:
debug_supervision_alignment(synthetic_data, tokenizerGemma, n=20)
debug_supervision_alignment(gold_examples, tokenizerGemma, n=20)

--- Example 0 ---
EXPECTED:
'<answer> (19 - (14 * (38 - 43))) </answer><eos>'
DECODED LABELS:
'<answer> (19 - (14 * (38 - 43))) </answer><eos>'

--- Example 1 ---
EXPECTED:
'<answer> ((88 + 76) / (82 / 25)) </answer><eos>'
DECODED LABELS:
'<answer> ((88 + 76) / (82 / 25)) </answer><eos>'

--- Example 2 ---
EXPECTED:
'<answer> (73 + (34 - 67)) </answer><eos>'
DECODED LABELS:
'<answer> (73 + (34 - 67)) </answer><eos>'

--- Example 3 ---
EXPECTED:
'<answer> (93 - (78 - 46)) </answer><eos>'
DECODED LABELS:
'<answer> (93 - (78 - 46)) </answer><eos>'

--- Example 4 ---
EXPECTED:
'<answer> ((49 * 4) / (33 - 26)) </answer><eos>'
DECODED LABELS:
'<answer> ((49 * 4) / (33 - 26)) </answer><eos>'

--- Example 5 ---
EXPECTED:
'<answer> ((62 + 36) + (20 - 54)) </answer><eos>'
DECODED LABELS:
'<answer> ((62 + 36) + (20 - 54)) </answer><eos>'

--- Example 6 ---
EXPECTED:
'<answer> (73 - (95 - 67)) </answer><eos>'
DECODED LABELS:
'<answer> (73 - (95 - 67)) </answer><eos>'

--- Example 7 ---
EXPECTED:
'<answer> (23 + (19 * (36 - 32))) </answer><eos>'
DECODED LABELS:
'<answer> (23 + (19 * (36 - 32))) </answer><eos>'

--- Example 8 ---
EXPECTED:
'<answer> (32 - ((17 + 21) / 2)) </answer><eos>'
DECODED LABELS:
'<answer> (32 - ((17 + 21) / 2)) </answer><eos>'

--- Example 9 ---
EXPECTED:
'<answer> (57 - (23 * (54 - 52))) </answer><eos>'
DECODED LABELS:
'<answer> (57 - (23 * (54 - 52))) </answer><eos>'

--- Example 10 ---
EXPECTED:
'<answer> ((3 * (70 - 18)) - 74) </answer><eos>'
DECODED LABELS:
'<answer> ((3 * (70 - 18)) - 74) </answer><eos>'

--- Example 11 ---
EXPECTED:
'<answer> (78 - (67 / 67)) </answer><eos>'
DECODED LABELS:
'<answer> (78 - (67 / 67)) </answer><eos>'

--- Example 12 ---
EXPECTED:
'<answer> ((28 - 67) * (88 - 89)) </answer><eos>'
DECODED LABELS:
'<answer> ((28 - 67) * (88 - 89)) </answer><eos>'

--- Example 13 ---
EXPECTED:
'<answer> (94 + (46 - 79)) </answer><eos>'
DECODED LABELS:
'<answer> (94 + (46 - 79)) </answer><eos>'

--- Example 14 ---
EXPECTED:
'<answer> ((36 - 31) / (21 / 84)) </answer><eos>'
DECODED LABELS:
'<answer> ((36 - 31) / (21 / 84)) </answer><eos>'

--- Example 15 ---
EXPECTED:
'<answer> 37 + 17 - 1 </answer><eos>'
DECODED LABELS:
'<answer> 37 + 17 - 1 </answer><eos>'

--- Example 16 ---
EXPECTED:
'<answer> (36 - ((35 + 7) / 7)) </answer><eos>'
DECODED LABELS:
'<answer> (36 - ((35 + 7) / 7)) </answer><eos>'

--- Example 17 ---
EXPECTED:
'<answer> ((90 * 63) / (86 - 16)) </answer><eos>'
DECODED LABELS:
'<answer> ((90 * 63) / (86 - 16)) </answer><eos>'

--- Example 18 ---
EXPECTED:
'<answer> (9 * (13 - 10)) </answer><eos>'
DECODED LABELS:
'<answer> (9 * (13 - 10)) </answer><eos>'

--- Example 19 ---
EXPECTED:
'<answer> (3 - (11 - 67)) </answer><eos>'
DECODED LABELS:
'<answer> (3 - (11 - 67)) </answer><eos>'

All checked examples look aligned.

--- Example 0 ---
EXPECTED:
'<answer> 30 + 27 + 40 </answer><eos>'
DECODED LABELS:
'<answer> 30 + 27 + 40 </answer><eos>'

--- Example 1 ---
EXPECTED:
'<answer> (62 + 44) - 11 </answer><eos>'
DECODED LABELS:
'<answer> (62 + 44) - 11 </answer><eos>'

--- Example 2 ---
EXPECTED:
'<answer> 41 + 14 + 16 </answer><eos>'
DECODED LABELS:
'<answer> 41 + 14 + 16 </answer><eos>'

--- Example 3 ---
EXPECTED:
'<answer> 80 - (74 - 61) </answer><eos>'
DECODED LABELS:
'<answer> 80 - (74 - 61) </answer><eos>'

--- Example 4 ---
EXPECTED:
'<answer> ((83 + 61) - 99) </answer><eos>'
DECODED LABELS:
'<answer> ((83 + 61) - 99) </answer><eos>'

--- Example 5 ---
EXPECTED:
'<answer> (64 - 62) + (97 - 49) </answer><eos>'
DECODED LABELS:
'<answer> (64 - 62) + (97 - 49) </answer><eos>'

--- Example 6 ---
EXPECTED:
'<answer> (94 - 78) - 1 </answer><eos>'
DECODED LABELS:
'<answer> (94 - 78) - 1 </answer><eos>'

--- Example 7 ---
EXPECTED:
'<answer> ((95 + 74) - (48 + 21)) </answer><eos>'
DECODED LABELS:
'<answer> ((95 + 74) - (48 + 21)) </answer><eos>'

--- Example 8 ---
EXPECTED:
'<answer> 1 + 64 + 17 </answer><eos>'
DECODED LABELS:
'<answer> 1 + 64 + 17 </answer><eos>'

--- Example 9 ---
EXPECTED:
'<answer> 72 - 46 - 3 </answer><eos>'
DECODED LABELS:
'<answer> 72 - 46 - 3 </answer><eos>'

--- Example 10 ---
EXPECTED:
'<answer> ((34 + 63) - 15) </answer><eos>'
DECODED LABELS:
'<answer> ((34 + 63) - 15) </answer><eos>'

--- Example 11 ---
EXPECTED:
'<answer> ((98 - 18) + 17) </answer><eos>'
DECODED LABELS:
'<answer> ((98 - 18) + 17) </answer><eos>'

--- Example 12 ---
EXPECTED:
'<answer> 60 - (61 - 47) </answer><eos>'
DECODED LABELS:
'<answer> 60 - (61 - 47) </answer><eos>'

--- Example 13 ---
EXPECTED:
'<answer> 19 + 49 - 16 </answer><eos>'
DECODED LABELS:
'<answer> 19 + 49 - 16 </answer><eos>'

--- Example 14 ---
EXPECTED:
'<answer> 56 + 37 - 28 </answer><eos>'
DECODED LABELS:
'<answer> 56 + 37 - 28 </answer><eos>'

--- Example 15 ---
EXPECTED:
'<answer> 63 - 36 - 6 </answer><eos>'
DECODED LABELS:
'<answer> 63 - 36 - 6 </answer><eos>'

--- Example 16 ---
EXPECTED:
'<answer> (57 + 11) + 1 </answer><eos>'
DECODED LABELS:
'<answer> (57 + 11) + 1 </answer><eos>'

--- Example 17 ---
EXPECTED:
'<answer> ((36 + 74) - 81) </answer><eos>'
DECODED LABELS:
'<answer> ((36 + 74) - 81) </answer><eos>'

--- Example 18 ---
EXPECTED:
'<answer> (96 - 89) + 73 </answer><eos>'
DECODED LABELS:
'<answer> (96 - 89) + 73 </answer><eos>'

All checked examples look aligned.

# Learning student again

In [44]:
import gc

modelGemma.config.use_cache = False
modelGemma.gradient_checkpointing_enable() 

del modelQwen
gc.collect()
torch.cuda.empty_cache()

In [45]:
del trainer
gc.collect()
torch.cuda.empty_cache()

In [46]:
combined_examples = synthetic_data + gold_examples_balanced
random.shuffle(combined_examples)

combined_dataset = Dataset.from_list(combined_examples)
tokenized_combined_dataset = combined_dataset.map(
    preprocess_student,
    remove_columns=combined_dataset.column_names
)

print("synthetic:", len(synthetic_data))
print("gold:", len(gold_examples_balanced))
print("combined:", len(combined_examples))

Map:   0%|          | 0/115 [00:00<?, ? examples/s]

synthetic: 100
gold: 15
combined: 115

In [47]:
gold_training_args = TrainingArguments(
    output_dir='./gemma_student_gold_mix',
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    num_train_epochs=1,
    learning_rate=1e-4,
    weight_decay=0.01,
    logging_steps=10,
    save_steps=200,
    bf16=torch.cuda.is_available(),
    report_to='none'
)

trainer_gold = Trainer(
    model=modelGemma,
    args=gold_training_args,
    train_dataset=tokenized_combined_dataset,
    data_collator=data_collator
)

trainer_gold.train()

TrainOutput(global_step=8, training_loss=0.3983832895755768, metrics={'train_runtime': 78.1623, 'train_samples_per_second': 1.471, 'train_steps_per_second': 0.102, 'total_flos': 66036542264064.0, 'train_loss': 0.3983832895755768, 'epoch': 1.0})

In [48]:
modelGemma.gradient_checkpointing_disable()
modelGemma.config.use_cache = True
modelGemma.eval()

train_debug = train_part.select(range(20))

debug_result = evaluate_student(
    train_debug,
    modelGemma,
    tokenizerGemma,
    max_new_tokens=96
)

print('train debug after GOLD:', debug_result)

train debug after GOLD: {'task_accuracy': 0.1, 'correct_answers': 2, 'total_answers': 20}

In [49]:
debug_subset = eval_part.select(range(5))

for i, example in enumerate(debug_subset):
    prompt = build_student_messages(example)
    answer = generate_student_answer(
        modelGemma,
        tokenizerGemma,
        prompt,
        max_new_tokens=96
    )
    print(f'\n--- Example {i} ---')
    print('Target:', example['target'])
    print('Nums:', example['nums'])
    print('Student output:')
    print(repr(answer))

--- Example 0 ---
Target: 27
Nums: [64, 2, 52, 17]
Student output:
'<answer> (52 - (17 * 2)) </answer>'

--- Example 1 ---
Target: 28
Nums: [93, 33, 22, 17]
Student output:
'<answer> (93 - (33 - 22)) </answer>'

--- Example 2 ---
Target: 71
Nums: [25, 56, 73, 29]
Student output:
'<answer> (73 - (25 + 29)) </answer>'

--- Example 3 ---
Target: 85
Nums: [17, 81, 78, 10]
Student output:
'<answer> (78 - (17 * 81)) </answer>'

--- Example 4 ---
Target: 98
Nums: [55, 2, 45]
Student output:
'<answer> (55 - (2 + 45)) </answer>'

In [50]:
eval_after_gold = evaluate_student(
    eval_part.select(range(100)),
    modelGemma,
    tokenizerGemma,
    max_new_tokens=96
)

print('after GOLD:', eval_after_gold)

after GOLD: {'task_accuracy': 0.08, 'correct_answers': 8, 'total_answers': 100}

In [52]:
def pick_best_equation_sampled(model, tokenizer, nums, target, n_samples=32):
    example = {'nums': nums, 'target': target}
    messages = build_student_messages(example)
    
    text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False
    )
    
    inputs = tokenizer([text], return_tensors='pt').to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=96,
            do_sample=True,
            temperature=0.7, 
            top_p=0.95,
            num_return_sequences=n_samples,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id
        )
        
    prompt_len = inputs['input_ids'].shape[-1]
    fallback_equation = ""
    
    for i in range(outputs.shape[0]):
        new_tokens = outputs[i][prompt_len:]
        candidate_text = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        
        is_ok, _ = is_teacher_answer_correct(candidate_text, nums, target)
        
        extracted = extract_answer_block(candidate_text)
        equation = extract_expression(extracted) if extracted else candidate_text
        
        if fallback_equation == "":
            fallback_equation = equation 
            
        if is_ok:
            return True, equation 
            
    return False, fallback_equation

In [58]:
import pandas as pd
import ast
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning)

test_csv_path = '/kaggle/input/competitions/distillation-challenge-2026/test_public.csv'
df_test = pd.read_csv(test_csv_path)

def parse_nums(value):
    if isinstance(value, str):
        return ast.literal_eval(value) 
    return value 

if 'nums' in df_test.columns:
    df_test['nums'] = df_test['nums'].apply(parse_nums)

ds_test = df_test.to_dict('records')
submission_rows = []

modelGemma.eval()

print(f"Generating predictions for {len(ds_test)} rows...")
for index, expression in enumerate(tqdm(ds_test)):
    nums = expression["nums"]
    target = expression["target"]
    row_id = expression.get("id", index)

    is_valid, best_equation = pick_best_equation_sampled(
        modelGemma,
        tokenizerGemma,
        nums,
        target,
        n_samples=32
    )

    submission_rows.append({
        "id": row_id,
        "equation": best_equation
    })


submission_df = pd.DataFrame(submission_rows)
submission_df.to_csv("submission.csv", index=False)

print("\nSuccessfully saved submission.csv!")
display(submission_df.head())

Generating predictions for 2000 rows...

  0%|          | 0/2000 [00:00<?, ?it/s]

Successfully saved submission.csv!

   id          equation
0   0  (68 - (11 + 83))
1   1   (9 * (71 - 66))
2   2    51 - (82 - 51)
3   3  (97 + (59 * 52))
4   4    (74 + 98) - 20